### ISSUE TITLE
_Index is not a valid member of ModuleScript "ReplicatedStorage.BridgeNet"

### ISSUE THREAD

**Issue by LawMixer** [ffrostflame/BridgeNet#18]
This is on the latest version by the way, and I don't have the proper module.

**Comment by ffrostflame** [comment]
Looks like I made a mistake with the .rbxm release. Will be fixed by tonight

**Comment by LawMixer** [comment]
Alright, thank you.

**Comment by ffrostflame** [comment]
Solved in 1.8.5
