### ISSUE TITLE
Queueing System Fully Broken

### ISSUE THREAD

**Issue by MELON-Om4r** [ffrostflame/BridgeNet#32]
The queueing functionality seems to be pretty broken. I have fixed a big part of it but there still remain a few issues.
PR: https://github.com/ffrostflame/BridgeNet/pull/31

**Comment by ffrostflame** [comment]
I need to see a repro for this. I can't reproduce any issues besides the ones I already know about (which aren't very major)

**Comment by ffrostflame** [comment]
nevermind lol I see the issue. merged your pr
