### ISSUE TITLE
Develop a testing framework with integration properties specialized for BridgeNet

### ISSUE THREAD

**Issue by sinlerdev** [ffrostflame/BridgeNet#34]
As BridgeNet gets more and more complex, the need for an automated testing framework becomes crucial. While I am aware of the fact that BridgeNet has an *okay* testing technique for testing *normal cases*, it becomes a nightmare to account for edge cases that require evalution for every output and input.

Additionally, using a pre-made testing framework like TestEZ or BoatTEST *(boatbomber's testing framework)* will not exactly fit the requirements for a testing framework that a networking library needs.

We need a framework that specifically allows us to:

1. Test everything from a single codebase on the client, and the communication infrastructure is managed by the Framework through a helper function.
2. Evaluate every output and input, accounting for edge cases
3. The ability to scale well by dividing multiple test cases into suites *(if it makes sense to do so)*.

I'm already willing to implement it and make a PR, however, I am looking to have a discussion about the design of the overall framework to avoid counter-productive patterns.

**Comment by sinlerdev** [comment]
a possible usage of this framework might look like this:
```lua
local expect = require(...) -- this is here to indicate that there will be no function environment manipulation at all

return {
    ["TestCase"] = function(askServer)
        askServer(function() 
            remoteEventReference.OnServerEvent:Connect(args)
                expect(args).to.equal(ARGS_TO_SEND)
            end
        end)

        remoteEventReference:FireServer(ARGS_TO_SEND)
    end, ...
}

```

**Comment by sinlerdev** [comment]
After thinking about this for some time, I think I have the right theoretical implementation.

Here's how I see it:

First, the server reads through all the test files *(.spec)*, and then passes a utility function that is used to create remote functions using the provided functions and then signals to all the clients using a remote event telling them to start running the tests.

After that, each client will go through all the test files and then pass a utility function that is used to fire the respective remote function and return the results coming from `InvokeServer`.

**Comment by ffrostflame** [comment]
I've thought a lot about how a testing framework should operate when testing something like BridgeNet, and I don't really think that we need to communicate client-server at all. I think a more standard form of automated testing is okay- after all something like the following works:
```lua
local flag = false
bridge:Connect(function()
    flag = true
end)

expect.delayed.to.be.ok(function() return flag == true end)
```
So some form of framework is still preferable- in fact, there's already a pretty decent gap when it comes to that... I've had plans for an automated testing framework for a while- I just have other projects I've been working on, such as 2.0.0-rc4, and some other projects I'm a bit more invested in.

**Comment by sinlerdev** [comment]
The reasoning behind communication is that we can write tests from a single codebase, increasing production and time. 

Your solution is okay, however, when you write another test case, you would still write it in two files, one on the server and the another on the client, which is incredibly inefficient.

Another thing with this model is that you can know what is happening at the first glance without digging in and searching for what is actually happening, because both the server code and the client code is in one codebase written in an understandable format.

**Comment by ffrostflame** [comment]
I think the opposite though- the server and client are 2 separate codebases. Why should they be tested from one file? Combining these two codebases to be tested under one roof could cause readability issues imo.

**Comment by sinlerdev** [comment]
Why would it cause readability issues though?

**Comment by sinlerdev** [comment]
After some thinking, I am starting to release that a cross-communication model might not be the best as that will likely introduce varies issues and limitations.

A standard solution for both the server and the client would be preferred, I agree.

**Comment by ffrostflame** [comment]
Sure, go ahead

**Comment by sinlerdev** [comment]
implementation: #35
