### ISSUE TITLE
BridgeNet.ServerBridge:118: attempt to index nil with '_connections'

### ISSUE THREAD

**Issue by evanchan0819** [ffrostflame/BridgeNet#4]
![image](https://user-images.githubusercontent.com/47493765/183858357-10845b1c-8de2-43f7-8a90-2557c0d8c499.png)

**Comment by evanchan0819** [comment]
@ffrostflame

**Comment by ffrostflame** [comment]
Can you update your BridgeNet? Line 118 is an if statement. There's a chance it'll fix your issue too

**Comment by evanchan0819** [comment]
ok

**Comment by evanchan0819** [comment]
oh yeah and you forgot to do
`	CreateUUID = serdeLayer.CreateUUID,
	PackUUID = serdeLayer.PackUUID,
	UnpackUUID = serdeLayer.UnpackUUID,
	
	DictionaryToTable = serdeLayer.DictionaryToTable,`
in BridgeNet module

**Comment by evanchan0819** [comment]
nope, didn't fix it.
theres this error too
```lua
debug.profileEnd() - No active profile annotation. At: Stack Begin
Script 'ReplicatedStorage.RobloxianFramework.Shared.Network.BridgeNet.ServerBridge', Line 126
Stack End
```

**Comment by evanchan0819** [comment]
I forked the module to fix it.

**Comment by ffrostflame** [comment]
Do you mind opening a pr? I think this is because at the moment, BridgeNet doesn't support firing bridge objects w/o an object connected.

**Comment by evanchan0819** [comment]
no, i think my error is because the client bridge is created earlier than the server one.

**Comment by ffrostflame** [comment]
that would be why. Honestly, this is an embarrassingly large vulnerability which I'll get on fixing atm

**Comment by evanchan0819** [comment]
how i fixed it is using a remote function to tell the server to create a bridge first

**Comment by evanchan0819** [comment]
> oh yeah and you forgot to do
> 
> ```
> 	CreateUUID = serdeLayer.CreateUUID,
> 	PackUUID = serdeLayer.PackUUID,
> 	UnpackUUID = serdeLayer.UnpackUUID,
> 	
> 	DictionaryToTable = serdeLayer.DictionaryToTable,
> ```
> 
> in BridgeNet module
also, you need to fix this because indexing BridgeNet.CreateUUID is not going to work without it.

**Comment by ffrostflame** [comment]
Yep I know, that's already done in this update. Just haven't pushed it out yet

**Comment by ffrostflame** [comment]
oop- this is already implemented on the client, I just forgot to do it on the server.

**Comment by evanchan0819** [comment]
ty for making this module though, just gotta fix some bugs.

**Comment by ffrostflame** [comment]
Yeah, that's a good idea. I'll defo implement.

I didn't really consider user code erroring in connections when I wrote that, so thank you for pointing it out.

**Comment by ffrostflame** [comment]
Oh don't worry I'm not taking offense, I'm ecstatic these things are being pointed out- it's in alpha for a reason. I'm very glad you're pointing out these things because it's how the module is going to get better

**Comment by evanchan0819** [comment]
ok.
do you want my version of BridgeNet?

**Comment by ffrostflame** [comment]
I implemented your changes on my side with some additional comments (I'm actively developing right now) so I'm ok but thanks for the offer

**Comment by evanchan0819** [comment]
no problem, glad to help!
also one last thing is maybe you should add this inside Server/Client Bridge.new():
```lua
local found = ServerBridge.from(remoteName)
if found ~= nil then
	return found
end
```

**Comment by ffrostflame** [comment]
Yeah that'd be a pretty nice QoL I didn't consider, thanks for pointing it out.

**Comment by evanchan0819** [comment]
Thanks For All The Help!
